/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form;

import com.connection.DatabaseConnection;
import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.List;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.net.URL;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author shaitozen
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */ 
    public boolean hideOnOff = true;
    private java.sql.Connection conn;
    final private String DRIVER = "com.mysql.jdbc.Driver";
    final private String USER = "root";
    final private String PASSWORD = "pogisiato";
    final private String URL = "jdbc:mysql://localhost:3306/";
    final private String DATABASE = "vapeshop";
    public String query;
    public PreparedStatement pst = null;
    public ResultSet rs = null;
    
     private static final String PASSWORD_REGEX =
            "^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{4,8}$";
     
     private static final String COMPLEX_PASSWORD_REGEX =
            "^(?:(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])|" +
            "(?=.*\\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|" +
            "(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|" +
            "(?=.*\\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))(?!.*(.)\\1{2,})" +
            "[A-Za-z0-9!~<>,;:_=?*+#.\"&§%°()\\|\\[\\]\\-\\$\\^\\@\\/]" +
            "{8,32}$";
     
     private static final Pattern PASSWORD_PATTERN =
                                    Pattern.compile(COMPLEX_PASSWORD_REGEX);
    
    public LoginFrame() {
        initComponents();
       
        
        setIconImage();
        xMarkUsername.setVisible(false);
          xMarkPassword.setVisible(false);
        lbUsernameError.setVisible(false);
         lbPasswordError.setVisible(false);
         
        
    }
 
    
   
    
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/Icon-20.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hideIcon = new javax.swing.JLabel();
        xMarkPassword = new javax.swing.JLabel();
        xMarkUsername = new javax.swing.JLabel();
        lbUsernameError = new javax.swing.JLabel();
        lbPasswordError = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Form");
        setBackground(new java.awt.Color(185, 221, 217));
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(185, 221, 217));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hideIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hide_off_20.png"))); // NOI18N
        hideIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideIconMouseClicked(evt);
            }
        });
        jPanel1.add(hideIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        xMarkPassword.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        xMarkPassword.setForeground(new java.awt.Color(102, 102, 102));
        xMarkPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x_icon.png"))); // NOI18N
        xMarkPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMarkPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(xMarkPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 20, 20));

        xMarkUsername.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        xMarkUsername.setForeground(new java.awt.Color(102, 102, 102));
        xMarkUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x_icon.png"))); // NOI18N
        xMarkUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMarkUsernameMouseClicked(evt);
            }
        });
        jPanel1.add(xMarkUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 30, 20));

        lbUsernameError.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lbUsernameError.setForeground(new java.awt.Color(204, 0, 0));
        lbUsernameError.setText("* Username does not exist.");
        jPanel1.add(lbUsernameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 260, -1));

        lbPasswordError.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lbPasswordError.setForeground(new java.awt.Color(204, 0, 0));
        lbPasswordError.setText("* Wrong password, please retry.");
        jPanel1.add(lbPasswordError, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 260, -1));

        lbUsername.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(153, 153, 153));
        lbUsername.setText("Username");
        lbUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbUsernameMousePressed(evt);
            }
        });
        jPanel1.add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 260, 30));

        lbPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(153, 153, 153));
        lbPassword.setText("Password");
        lbPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbPasswordMousePressed(evt);
            }
        });
        jPanel1.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 260, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icon-256.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icon-40_user.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icon-40_lock.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtPassword.setBackground(new java.awt.Color(185, 221, 217));
        txtPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 51, 102));
        txtPassword.setBorder(null);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 260, 30));

        txtUsername.setBackground(new java.awt.Color(185, 221, 217));
        txtUsername.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 51, 102));
        txtUsername.setBorder(null);
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 260, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/line.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 300, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/line.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, -1));

        btnLogin.setBackground(new java.awt.Color(0, 255, 51));
        btnLogin.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(102, 51, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 210, 50));

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Made by El Niño R. Malapogi 2021 ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUsernameMousePressed
        // TODO add your handling code here:
        txtUsername.setVisible(true);
     
        txtUsername.requestFocus();
          
     
        
    }//GEN-LAST:event_lbUsernameMousePressed

    private void lbPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPasswordMousePressed
        // TODO add your handling code here:
        txtPassword.setVisible(true);
      
         txtPassword.requestFocus();
           
    
    }//GEN-LAST:event_lbPasswordMousePressed

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        // TODO add your handling code here:
          
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
       
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        // TODO add your handling code here:
         lbUsername.setVisible(false);
            xMarkUsername.setVisible(false);
        if(txtUsername.getText().isEmpty())
             lbUsername.setVisible(true);   
             xMarkUsername.setVisible(true);
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
           lbPassword.setVisible(false);
               xMarkPassword.setVisible(false);
        if(txtPassword.getText().isEmpty())
             lbPassword.setVisible(true);   
         xMarkPassword.setVisible(true);
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
           lbUsername.setVisible(false);
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
           lbPassword.setVisible(false);
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void xMarkUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMarkUsernameMouseClicked
        // TODO add your handling code here:
        txtUsername.setText("");
          lbUsername.setVisible(false);
          xMarkUsername.setVisible(false);
        if(txtUsername.getText().isEmpty())
             lbUsername.setVisible(true);   
        
    }//GEN-LAST:event_xMarkUsernameMouseClicked

    private void hideIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideIconMouseClicked
        // TODO add your handling code here
        
        if(hideOnOff == true){
            Image photo = new ImageIcon(this.getClass().getResource("/resources/hide_on_20.png")).getImage();
            hideIcon.setIcon(new ImageIcon(photo));
            hideOnOff = false;
            txtPassword.setEchoChar((char) 0);
        }else{
            Image photo = new ImageIcon(this.getClass().getResource("/resources/hide_off_20.png")).getImage();
            hideIcon.setIcon(new ImageIcon(photo));
            hideOnOff = true;
            txtPassword.setEchoChar('*');
        }
        
        
    }//GEN-LAST:event_hideIconMouseClicked

    private void xMarkPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMarkPasswordMouseClicked
        // TODO add your handling code here:
         txtPassword.setText("");
          lbPassword.setVisible(false);
          xMarkPassword.setVisible(false);
        if(txtPassword.getText().isEmpty())
             lbPassword.setVisible(true);  
    }//GEN-LAST:event_xMarkPasswordMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
//        try {
//            if (PASSWORD_PATTERN.matcher(txtPassword.getText()).matches()) {
//           JOptionPane.showMessageDialog(this, "The password is valid");
//        }
//        else {
//             JOptionPane.showMessageDialog(this, "The password is invalid");
//        }
//        } catch (Exception e) {
//        }
        
        try {
            Class.forName(DRIVER);
            conn = DriverManager.getConnection(URL + DATABASE, USER, PASSWORD);
            query = "SELECT * FROM user_management WHERE username=?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, txtUsername.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                lbUsernameError.setVisible(false);
                
                try {
            Class.forName(DRIVER);
            conn = DriverManager.getConnection(URL + DATABASE, USER, PASSWORD);
            query = "SELECT * FROM user_management WHERE username=? and password = ?";
            pst = conn.prepareStatement(query);
            pst.setString(1, txtUsername.getText());
            pst.setString(2, txtPassword.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                lbPasswordError.setVisible(false);
                String userType = rs.getString("user_type");
                
                if(rs.getString("user_type").equals("Cashier")) {
                    
                    CashierFrame cashierFrame = new CashierFrame();
                    cashierFrame.lbLastname.setText("Name: " + rs.getString("last_name"));
                    cashierFrame.setCashierName(rs.getString("last_name"));
                    cashierFrame.setUsername(rs.getString("username"));
                    cashierFrame.setVisible(true);
                    dispose();
                }
      
                else  if(userType.equals("Owner") || userType.equals("Manager")){
                    ManagerFrame managerFrame = new ManagerFrame();
                    managerFrame.gender = rs.getBoolean("gender");
                    managerFrame.lbUserType.setText(rs.getString("user_type"));
                    managerFrame.lbLastname.setText("Name: " + rs.getString("last_name"));
                    managerFrame.username = rs.getString("username");
           
                    managerFrame.genderIcon();
                    
                    managerFrame.setVisible(true);
                    dispose();
                }
            } else {
               lbPasswordError.setVisible(true);
            }
            conn.close();
             
        } catch (Exception e) {
        }
           
            } else {
               lbUsernameError.setVisible(true);
            }
            conn.close();
            
        } catch (Exception e) {
        }
             
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel hideIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPasswordError;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JLabel lbUsernameError;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel xMarkPassword;
    private javax.swing.JLabel xMarkUsername;
    // End of variables declaration//GEN-END:variables
}
